export const LIST_CATEGORY_REQUEST = "LIST_CATEGORY_REQUEST";
export const LIST_CATEGORY_SUCCESS = "LIST_CATEGORY_SUCCESS";
export const LIST_CATEGORY_FAILED = "LIST_CATEGORY_FAILED";

export const CREATE_CATEGORY_REQUEST = "CREATE_CATEGORY_REQUEST";
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORY_SUCCESS";
export const CREATE_CATEGORY_FAILED = "CREATE_CATEGORY_FAILED";

export const REMOVE_CATEGORY_REQUEST = "REMOVE_CATEGORY_REQUEST";
export const REMOVE_CATEGORY_SUCCESS = "REMOVE_CATEGORY_SUCCESS";
export const REMOVE_CATEGORY_FAILED = "REMOVE_CATEGORY_FAILED";

export const DETAILS_CATEGORY_REQUEST = "DETAILS_CATEGORY_REQUEST";
export const DETAILS_CATEGORY_SUCCESS = "DETAILS_CATEGORY_SUCCESS";
export const DETAILS_CATEGORY_FAILED = "DETAILS_CATEGORY_FAILED";

export const UPDATE_CATEGORY_REQUEST = "UPDATE_CATEGORY_REQUEST";
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORY_SUCCESS";
export const UPDATE_CATEGORY_FAILED = "UPDATE_CATEGORY_FAILED";

export const GET_SUB_CATEGORY_REQUEST = "GET_SUB_CATEGORY_REQUEST";
export const GET_SUB_CATEGORY_SUCCESS = "GET_SUB_CATEGORY_SUCCESS";
export const GET_SUB_CATEGORY_FAILED = "GET_SUB_CATEGORY_FAILED";