export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAILED = "CREATE_PRODUCT_FAILED";

export const LIST_PRODUCT_BY_COUNT_REQUEST = "LIST_PRODUCT_BY_COUNT_REQUEST";
export const LIST_PRODUCT_BY_COUNT_SUCCESS = "LIST_PRODUCT_BY_COUNT_SUCCESS";
export const LIST_PRODUCT_BY_COUNT_FAILED = "LIST_PRODUCT_BY_COUNT_FAILED";

export const UPDATE_PRODUCT_REQUEST = "UPDATE_PRODUCT_REQUEST";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_FAILED = "UPDATE_PRODUCT_FAILED";

export const DETAILS_PRODUCT_REQUEST = "DETAILS_PRODUCT_REQUEST";
export const DETAILS_PRODUCT_SUCCESS = "DETAILS_PRODUCT_SUCCESS";
export const DETAILS_PRODUCT_FAILED = "DETAILS_PRODUCT_FAILED";

export const REMOVE_PRODUCT_REQUEST = "REMOVE_PRODUCT_REQUEST";
export const REMOVE_PRODUCT_SUCCESS = "REMOVE_PRODUCT_SUCCESS";
export const REMOVE_PRODUCT_FAILED = "REMOVE_PRODUCT_FAILED";