export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const CREATE_PRODUCT_FAILED = "CREATE_PRODUCT_FAILED";

export const LIST_PRODUCT_BY_COUNT_REQUEST = "LIST_PRODUCT_BY_COUNT_REQUEST";
export const LIST_PRODUCT_BY_COUNT_SUCCESS = "LIST_PRODUCT_BY_COUNT_SUCCESS";
export const LIST_PRODUCT_BY_COUNT_FAILED = "LIST_PRODUCT_BY_COUNT_FAILED";