export const LIST_SUB_CATEGORY_REQUEST = "LIST_SUB_CATEGORY_REQUEST";
export const LIST_SUB_CATEGORY_SUCCESS = "LIST_SUB_CATEGORY_SUCCESS";
export const LIST_SUB_CATEGORY_FAILED = "LIST_SUB_CATEGORY_FAILED";

export const CREATE_SUB_CATEGORY_REQUEST = "CREATE_SUB_CATEGORY_REQUEST";
export const CREATE_SUB_CATEGORY_SUCCESS = "CREATE_SUB_CATEGORY_SUCCESS";
export const CREATE_SUB_CATEGORY_FAILED = "CREATE_SUB_CATEGORY_FAILED";

export const REMOVE_SUB_CATEGORY_REQUEST = "REMOVE_SUB_CATEGORY_REQUEST";
export const REMOVE_SUB_CATEGORY_SUCCESS = "REMOVE_SUB_CATEGORY_SUCCESS";
export const REMOVE_SUB_CATEGORY_FAILED = "REMOVE_SUB_CATEGORY_FAILED";